// WOMENFOOTWEAR
export const GET_WOMENFOOTWEAR_REQUEST = "GET_WOMENFOOTWEAR_REQUEST";
export const GET_WOMENFOOTWEAR_SUCCESS = "GET_WOMENFOOTWEAR_SUCCESS";
export const GET_WOMENFOOTWEAR_FAILURE = "GET_WOMENFOOTWEAR_FAILURE";

// WOMENClothing

export const GET_WOMENCLOTHING_REQUEST = "GET_WOMENCLOTHING_REQUEST";
export const GET_WOMENCLOTHING_SUCCESS = "GET_WOMENCLOTHING_SUCCESS";
export const GET_WOMENCLOTHING_FAILURE = "GET_WOMENCLOTHING_FAILURE";
// WOMENccessories

export const GET_WOMENACCESSORIES_REQUEST = "GET_WOMENACCESSORIES_REQUEST";
export const GET_WOMENACCESSORIES_SUCCESS = "GET_WOMENACCESSORIES_SUCCESS";
export const GET_WOMENACCESSORIES_FAILURE = "GET_WOMENACCESSORIES_FAILURE";
